[[redirects]]
  from = "/api/*"
  to = "http://54.180.153.240:3000/:splat"
  status = 200

[[redirects]]
  from = "/baekjoon/*"
  to = "https://www.acmicpc.net/:splat"
  status = 200

[[redirects]]
  from = "/goorm/*"
  to = "https://level.goorm.io/:splat"
  status = 200
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

