[[redirects]]
  from = "/api/*"
  to = "http://39.116.153.159:4500/:splat"
  status = 200

[[redirects]]
  from = "/baekjoon/*"
  to = "https://www.acmicpc.net/:splat"
  status = 200

[[redirects]]
  from = "/goorm/*"
  to = "https://level.goorm.io/:splat"
  status = 200

[[redirects]]
  from = "/kapi/*"
  to = "https://kapi.kakao.com/:splat"
  status = 200

[[redirects]]
  from = "/kauth/*"
  to = "https://kauth.kakao.com/:splat"
  status = 200
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

