name: Deploy to EC2

on:
 push:
   branches:
     - main
   paths:
     - 'server/**'
jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
     - name: Deploy
       uses: fifsky/ssh-action@master
       with:
         host: ${{ secrets.EC2_HOST }}
         user: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           cd alog\server & git checkout main & git pull & npm install --production & pm2 reload ecosystem.config.js
